robot0:
  controller_manager: 
    ros__parameters: 
      diffdrive_controller: 
        type: diff_drive_controller/DiffDriveController
        update_rate: 0
      joint_state_broadcaster: 
        type: joint_state_broadcaster/JointStateBroadcaster
      update_rate: 50

  diffdrive_controller: 
    ros__parameters: 
      left_wheel_names: 
        - "left wheel motor"
      right_wheel_names: 
        - "right wheel motor"
      update_rate: 0
      use_stamped_vel: false
      wheel_radius: 0.033
      wheel_separation: 0.16
      odom_frame_id: "odom"

  joint_state_broadcaster: 
    ros__parameters: 
      extra_joints: 
        - LDS-01_secondary_motor
        - LDS-01_main_motor
